In [1]:
import numpy as np
import pandas as pd
from sklearn import svm, model_selection, preprocessing, pipeline, impute, feature_selection
from sklearn.experimental import enable_iterative_imputer
from itertools import chain, combinations, product
import math
import time

import warnings
from sklearn.exceptions import DataConversionWarning
warnings.filterwarnings(action='ignore', category=UserWarning)

In [2]:
data = pd.read_csv("insurance.csv")
data

GoodStudent         Age    SocioEcon RiskAversion VehicleYear  \
0            False       Adult        Prole  Adventurous       Older   
1            False      Senior        Prole     Cautious     Current   
2            False      Senior  UpperMiddle   Psychopath     Current   
3            False  Adolescent       Middle       Normal       Older   
4            False  Adolescent        Prole       Normal       Older   
...            ...         ...          ...          ...         ...   
19995        False       Adult        Prole  Adventurous       Older   
19996        False       Adult       Middle       Normal       Older   
19997        False      Senior  UpperMiddle       Normal     Current   
19998        False       Adult       Middle       Normal       Older   
19999        False       Adult       Middle       Normal       Older   

      ThisCarDam RuggedAuto  Accident    MakeModel DrivQuality  ... HomeBase  \
0       Moderate   EggShell      Mild      Economy        Poor  ...     City   
1           None   Football      None      Economy      Normal  ...     City   
2           None   Football      None  FamilySedan   Excellent  ...     City   
3           None   EggShell      None      Economy      Normal  ...   Suburb   
4       Moderate   Football  Moderate      Economy        Poor  ...     City   
...          ...        ...       ...          ...         ...  ...      ...   
19995       Mild   Football      Mild      Economy        Poor  ...     City   
19996       None       Tank      None  FamilySedan      Normal  ...   Suburb   
19997       None   Football      None       Luxury   Excellent  ...   Secure   
19998       None   Football      None  FamilySedan   Excellent  ...   Suburb   
19999       None       Tank      None  FamilySedan   Excellent  ...   Secure   

       AntiTheft  PropCost  OtherCarCost OtherCar   MedCost Cushioning Airbag  \
0          False   TenThou      Thousand     True  Thousand       Poor  False   
1           True  Thousand      Thousand     True  Thousand       Good   True   
2          False  Thousand      Thousand    False  Thousand       Good   True   
3          False  Thousand      Thousand     True  Thousand       Fair  False   
4          False   TenThou      Thousand    False  Thousand       Fair  False   
...          ...       ...           ...      ...       ...        ...    ...   
19995      False  Thousand      Thousand     True  Thousand       Fair  False   
19996      False  Thousand      Thousand     True  Thousand       Good  False   
19997       True   TenThou      Thousand    False  Thousand  Excellent   True   
19998      False  Thousand      Thousand     True  Thousand       Good   True   
19999      False  Thousand      Thousand     True  Thousand  Excellent   True   

        ILiCost DrivHist  
0      Thousand     Many  
1      Thousand     Zero  
2      Thousand      One  
3      Thousand     Zero  
4      Thousand     Many  
...         ...      ...  
19995  Thousand     Many  
19996  Thousand     Zero  
19997  Thousand     Zero  
19998  Thousand     Zero  
19999  Thousand     Zero  

[20000 rows x 27 columns]

In [3]:
#X = data[data.columns.drop(["RiskAversion", "Accident"])]
#y = data[["RiskAversion", "Accident"]]

X = data[data.columns.drop("Accident")]
y = data["Accident"]

X_train, X_test, y_train, y_test = model_selection.train_test_split(X, y)

In [4]:
le_X = preprocessing.OrdinalEncoder()
le_y = preprocessing.LabelEncoder()

X_train_en = le_X.fit_transform(X_train)
y_train_en = le_y.fit_transform(y_train)

In [5]:
clf = svm.SVC()
clf.fit(X_train_en, y_train_en)

SVC()

In [6]:
clf.predict(le_X.transform(X_test))

array([2, 2, 0, ..., 2, 2, 2])

In [7]:
# train an imputer 
imp = impute.SimpleImputer(missing_values=np.nan, strategy = "most_frequent")
#imp = impute.IterativeImputer(missing_values=np.nan, initial_strategy= "most_frequent")
imp.fit(X_train)

SimpleImputer(strategy='most_frequent')

In [8]:
prueba = X_test.head(1).to_numpy()
prueba[0][10:26] = np.nan
imp.transform(prueba)

array([[False, 'Adult', 'Middle', 'Normal', 'Older', 'None', 'Football',
        'FamilySedan', 'Excellent', 'Domino', False, 'Normal', False,
        'Thousand', False, 'FiveThou', 'City', False, 'Thousand',
        'Thousand', True, 'Thousand', 'Poor', False, 'Thousand', 'Zero']],
      dtype=object)

In [9]:
X_test.iloc[[1]]

GoodStudent    Age    SocioEcon RiskAversion VehicleYear ThisCarDam  \
17854        False  Adult  UpperMiddle       Normal     Current       None   

      RuggedAuto MakeModel DrivQuality     Mileage  ...  HomeBase AntiTheft  \
17854   Football    Luxury      Normal  TwentyThou  ...    Secure      True   

       PropCost OtherCarCost  OtherCar   MedCost Cushioning  Airbag   ILiCost  \
17854  Thousand     Thousand      True  Thousand       Good    True  Thousand   

      DrivHist  
17854     Zero  

[1 rows x 26 columns]

In [10]:
X_observed = X.columns[0:20]
X_unobserved = [x for x in X if x not in X_observed]

In [11]:
def powerset(iterable):
    s = list(iterable)
    tmp = list(chain.from_iterable(combinations(s, r) for r in range(len(s)+1)))
    return tmp

In [12]:
S = powerset(X_unobserved)
S.pop(0)

()

In [13]:
S[10][1]

'DrivHist'

In [14]:
def omega(variable, data) :
    return list(data[variable].unique())

In [15]:
omega("Age",X)

['Adult', 'Senior', 'Adolescent']

In [16]:
# OPCIONES PARA PREDICT
# Estimar con los datos la clase más probable
# Estimar con los datos la missing data y utilizar el algoritmo
clf.predict(le_X.transform(X_test.head(1).to_numpy()))

array([2])

In [34]:
prueba = X_test.head(1).to_numpy()

In [35]:
prueba[0][20:26] = np.nan

#prueba.iloc[0,20:26] = np.nan

In [19]:
clf.predict(le_X.transform(X_test.head(1)))

array([2])

In [20]:
X_observed

Index(['GoodStudent', 'Age', 'SocioEcon', 'RiskAversion', 'VehicleYear',
       'ThisCarDam', 'RuggedAuto', 'MakeModel', 'DrivQuality', 'Mileage',
       'Antilock', 'DrivingSkill', 'SeniorTrain', 'ThisCarCost', 'Theft',
       'CarValue', 'HomeBase', 'AntiTheft', 'PropCost', 'OtherCarCost'],
      dtype='object')

In [21]:
def reduce_dataset(instance, X,y) :
    columns = X.columns
    for i,value in enumerate(instance) :
        if isinstance(value, str) or not math.isnan(value) :
            X = X[X[columns[i]] == value]
            X = X.drop(columns[i], axis=1)
    y = y[[j for j in y.index if j in X.index]]
    return X,y

In [22]:
X['Age'] == "Adult"

0         True
1        False
2        False
3        False
4        False
         ...  
19995     True
19996     True
19997    False
19998     True
19999     True
Name: Age, Length: 20000, dtype: bool

In [23]:
X_test.head(1).to_numpy()

array([[False, 'Adult', 'Middle', 'Normal', 'Older', 'None', 'Football',
        'FamilySedan', 'Excellent', 'Domino', False, 'Expert', False,
        'Thousand', False, 'FiveThou', 'Secure', True, 'TenThou',
        'Thousand', True, 'Thousand', 'Fair', False, 'Thousand', 'Zero']],
      dtype=object)

In [24]:
reduced = reduce_dataset(prueba[0], X)

TypeError: reduce_dataset() missing 1 required positional argument: 'y'

In [25]:
reduced

NameError: name 'reduced' is not defined

In [26]:
def omega(variables, data) :
    domains = []
    for variable in variables :
        domains.append(data[variable].unique())
    return [p for p in product(*domains)]
    

# True if R is relevant
# False if R is irrelevant
def check_r(instances, set_R, data) : 
    #Type checking
    if isinstance(instances, pd.core.frame.DataFrame) :
        instances = instances.to_numpy()
    #Array for each instance
    out_array = []
    # For each instance:
    for instance in instances :
        # Check which are the missing variables
        columns = data.columns
        unobserved_vars = []
        for i,value in enumerate(instance) :
            if not isinstance(value, str) and math.isnan(value) :
                unobserved_vars.append(columns[i])
        # Check if R in unobserved
        #print(unobserved_vars)
        for R in set_R :
            if R not in unobserved_vars :
                print("Error")
                return
        # Impute and predict the instance
        complete_instance = imp.transform([instance])
        y = clf.predict(le_X.transform(complete_instance))
        # Obtain domain of R
        omega_R = omega(set_R, data)
        # For each value assignment r in omega(R)
        out_array.append(False)
        for value_assignment_r in omega_R :
            # Fill in values
            instance_alt = instance.copy()
            for i,value in enumerate(value_assignment_r) :
                instance_alt[list(data.columns).index(set_R[i])] = value
            #print(instance)
            #print(instance_alt)
            # Imputar y predecir 
            complete_instance_alt = imp.transform([instance_alt])
            y_alt = clf.predict(le_X.transform(complete_instance_alt))
            # Comparar con prediccion de instance
            #print(y, " == ", y_alt)
            if y != y_alt :
                out_array.pop()
                out_array.append(True)
                break
    return out_array

In [27]:
np.nan == np.nan

False

In [28]:
out = check_r(prueba, X_train.columns[15:20], X_train)
out

Error


In [29]:
for i in range(10,23) :
    print(list(range(i,i+3)),check_r(prueba, X_train.columns[i:i+3], X_train))

Error
[10, 11, 12] None
Error
[11, 12, 13] None
Error
[12, 13, 14] None
Error
[13, 14, 15] None
Error
[14, 15, 16] None
Error
[15, 16, 17] None
Error
[16, 17, 18] None
Error
[17, 18, 19] None
[18, 19, 20] [True]
[19, 20, 21] [True]
[20, 21, 22] [True]
[21, 22, 23] [True]
[22, 23, 24] [False]


In [30]:
def check_every_r(instances, data) :
    #Type checking
    if isinstance(instances, pd.core.frame.DataFrame) :
        instances = instances.to_numpy()
    #Array for each instance
    out_array = []
    # For each instance:
    for instance in instances :
        # Check which are the missing variables
        columns = data.columns
        unobserved_vars = []
        for i,value in enumerate(instance) :
            if not isinstance(value, str) and math.isnan(value) :
                unobserved_vars.append(columns[i])
        S = powerset(unobserved_vars)
        S.pop(0)
        relevant_sets = []
        irrelevant_sets = []
        for i in S :
            if check_r([instance], list(i), data)[0] :
                relevant_sets.append(i)
            else :
                irrelevant_sets.append(i)
        return relevant_sets, irrelevant_sets

In [31]:
def check_every_r_prune(instances, data) :
    #Type checking
    if isinstance(instances, pd.core.frame.DataFrame) :
        instances = instances.to_numpy()
    #Array for each instance
    out_array = []
    # For each instance:
    for instance in instances :
        # Check which are the missing variables
        columns = data.columns
        unobserved_vars = []
        for i,value in enumerate(instance) :
            if not isinstance(value, str) and math.isnan(value) :
                unobserved_vars.append(columns[i])
        S = powerset(unobserved_vars)
        S.pop(0)
        # Divide by length
        S_split = []
        size = 0
        for i in S :
            if len(i) != size:
                size = size + 1
                S_split.append([])
            S_split[-1].append(i)
        relevant_sets = []
        irrelevant_sets = []
        for i in range(0,len(S_split)) :
            for j in S_split[i] :
                # If relevant
                if check_r([instance], list(j), data)[0] :
                    relevant_sets.append(j)
                    # Apply prune
                    for k in range(i+1,len(S_split)) :
                        tmp = []
                        for l in S_split[k] :
                            if set(j).issubset(set(l)) :
                                relevant_sets.append(l)
                            else :
                                tmp.append(l)
                        S_split[k] = tmp
                # If irrelevant
                else :
                    irrelevant_sets.append(j)
        return relevant_sets, irrelevant_sets

In [32]:
prueba = X_test.head(1).to_numpy()
prueba[0][0:10] = np.nan
t0 = time.time()
relevant_sets, irrelevant_sets = check_every_r(prueba, X_train)
tf = time.time()
print("Brute force: ",tf-t0)

KeyboardInterrupt: 

In [37]:
t0 = time.time()
relevant_sets_p, irrelevant_sets_p = check_every_r_prune(prueba, X_train)
tf = time.time()
print("Prune: ",tf-t0)

Prune:  0.9932584762573242


In [ ]:
print(relevant_sets == relevant_sets_p)
print(irrelevant_sets == irrelevant_sets_p)

In [38]:
irrelevant_sets_p

[('OtherCar',),
 ('Cushioning',),
 ('Airbag',),
 ('ILiCost',),
 ('DrivHist',),
 ('OtherCar', 'Cushioning'),
 ('OtherCar', 'Airbag'),
 ('OtherCar', 'ILiCost'),
 ('OtherCar', 'DrivHist'),
 ('Cushioning', 'Airbag'),
 ('Cushioning', 'ILiCost'),
 ('Cushioning', 'DrivHist'),
 ('Airbag', 'ILiCost'),
 ('Airbag', 'DrivHist'),
 ('ILiCost', 'DrivHist'),
 ('OtherCar', 'Cushioning', 'Airbag'),
 ('OtherCar', 'Cushioning', 'ILiCost'),
 ('OtherCar', 'Cushioning', 'DrivHist'),
 ('OtherCar', 'Airbag', 'ILiCost'),
 ('OtherCar', 'Airbag', 'DrivHist'),
 ('OtherCar', 'ILiCost', 'DrivHist'),
 ('Cushioning', 'Airbag', 'ILiCost'),
 ('Cushioning', 'Airbag', 'DrivHist'),
 ('Cushioning', 'ILiCost', 'DrivHist'),
 ('Airbag', 'ILiCost', 'DrivHist'),
 ('OtherCar', 'Cushioning', 'Airbag', 'ILiCost'),
 ('OtherCar', 'Cushioning', 'Airbag', 'DrivHist'),
 ('OtherCar', 'Cushioning', 'ILiCost', 'DrivHist'),
 ('OtherCar', 'Airbag', 'ILiCost', 'DrivHist'),
 ('Cushioning', 'Airbag', 'ILiCost', 'DrivHist'),
 ('OtherCar', 'Cushi

In [176]:
# TODO FSS
X_red, y_red = reduce_dataset(prueba[0], X_train, y_train)

In [186]:
X_red

GoodStudent         Age SocioEcon RiskAversion VehicleYear ThisCarDam  \
19496        False       Adult     Prole  Adventurous       Older       None   
16430        False       Adult     Prole  Adventurous       Older       None   
16349        False       Adult     Prole       Normal       Older       None   
19828        False      Senior     Prole       Normal       Older       None   
14271        False  Adolescent     Prole       Normal       Older       Mild   
2786         False       Adult     Prole       Normal       Older       None   
8660         False  Adolescent     Prole  Adventurous       Older       None   
3439         False       Adult     Prole       Normal       Older       None   
1728         False  Adolescent     Prole       Normal       Older       None   
19518        False       Adult     Prole  Adventurous       Older       None   
14077        False  Adolescent     Prole  Adventurous       Older       Mild   
12976        False  Adolescent     Prole       Normal       Older       Mild   
1424         False       Adult     Prole       Normal       Older       None   
2926         False       Adult     Prole  Adventurous       Older       None   
16195        False  Adolescent     Prole  Adventurous       Older       None   
8651         False       Adult     Prole  Adventurous       Older       Mild   
12381        False       Adult     Prole       Normal       Older       Mild   
68           False       Adult     Prole       Normal       Older       Mild   
15771        False      Senior     Prole  Adventurous       Older       None   
16763        False       Adult     Prole       Normal       Older       Mild   
2773         False  Adolescent     Prole  Adventurous       Older       Mild   

      RuggedAuto    MakeModel DrivQuality     Mileage  
19496   EggShell      Economy        Poor  TwentyThou  
16430   EggShell      Economy        Poor    FiveThou  
16349   EggShell    SportsCar        Poor   FiftyThou  
19828   EggShell      Economy        Poor  TwentyThou  
14271   EggShell      Economy        Poor  TwentyThou  
2786    EggShell      Economy        Poor  TwentyThou  
8660    EggShell      Economy        Poor  TwentyThou  
3439    EggShell      Economy        Poor      Domino  
1728    EggShell      Economy        Poor  TwentyThou  
19518   EggShell    SportsCar        Poor   FiftyThou  
14077   EggShell      Economy        Poor   FiftyThou  
12976   EggShell      Economy        Poor   FiftyThou  
1424    EggShell      Economy        Poor  TwentyThou  
2926    Football  FamilySedan        Poor  TwentyThou  
16195   EggShell      Economy        Poor  TwentyThou  
8651    EggShell      Economy        Poor   FiftyThou  
12381   EggShell      Economy        Poor      Domino  
68      EggShell      Economy        Poor      Domino  
15771   EggShell      Economy        Poor  TwentyThou  
16763   EggShell      Economy        Poor  TwentyThou  
2773    EggShell      Economy        Poor      Domino

In [ ]:
y_red

In [188]:
#sel = feature_selection.GenericUnivariateSelect()
oe = preprocessing.OrdinalEncoder()
sel = feature_selection.RFECV(svm.SVC(kernel="linear"))
sel.fit_transform(oe.fit_transform(X_red),y_red)
sel.support_

array([False, False, False, False, False,  True, False, False, False,
       False])

In [189]:
print(X_red.columns[sel.support_ == False])

Index(['GoodStudent', 'Age', 'SocioEcon', 'RiskAversion', 'VehicleYear',
       'RuggedAuto', 'MakeModel', 'DrivQuality', 'Mileage'],
      dtype='object')


In [190]:
feature_selection.mutual_info_classif(oe.fit_transform(X_red),y_red)

array([0.        , 0.        , 0.        , 0.        , 0.14641003,
       0.68894937, 0.        , 0.        , 0.        , 0.13133067])

In [200]:
sel = feature_selection.GenericUnivariateSelect(feature_selection.chi2)
X_new = sel.fit_transform(oe.fit_transform(X_red),y_red)
sel.get_support()

array([False, False, False, False, False,  True, False, False, False,
       False])